<div class="sharrre-container">
	<div id="twitter" data-url="<?php echo get_page_link ($id); ?>" data-text="<?php echo $title; ?>" data-title="Tweet"></div>
	<div id="facebook" data-url="<?php echo get_page_link ($id);; ?>" data-text="<?php echo $title; ?>" data-title="Like"></div>
	<div id="googleplus" data-url="<?php echo get_page_link ($id);; ?>" data-text="<?php echo $title; ?>" data-title="+1"></div>
	<div id="pinterest" data-url="<?php echo get_page_link ($id);; ?>" data-text="<?php echo $title; ?>" data-title="Pin It"></div>
</div><!--/.sharrre-container-->