<div class="item-detail" data-cover='<?php echo $image_cover; ?>'>
	<div class="item-gallery theme-default">
		<?php if(!empty($download_url)) : ?>
		<div class="item-download">
			<a data-alt="<?php _e('Download'); ?>" href="<?php echo $download_url; ?>">
				<div class="icon-download-alt">&nbsp;</div>
			</a>
		</div>
		<?php endif; ?>				
		<video id="player" poster="<?php echo jeg_get_image($cover, '', $width, $height); ?>" controls="controls" preload="none">
		
			<?php if(!empty($mp4)) : ?>			
			<source type="video/mp4" src="<?php echo $mp4; ?>" />
			<?php endif; ?>
			
			<?php if(!empty($webm)) : ?>
			<source type="video/webm" src="<?php echo $webm; ?>" />
			<?php endif; ?>
			
			<?php if(!empty($ogg)) : ?>
			<source type="video/ogg" src="<?php echo $ogg; ?>" />
			<?php endif; ?>
			
			<!-- Fallback flash player for no-HTML5 browsers with JavaScript turned off -->
			<object width="<?php echo $width ?>" height="<?php echo $height; ?>" type="application/x-shockwave-flash" data="<?php echo JEG_CSS_URL . 'mediaelement/flashmediaelement.swf'; ?>"> 		
				<param name="movie" value="<?php echo JEG_CSS_URL . 'mediaelement/flashmediaelement.swf'; ?>" /> 
				<param name="flashvars" value="controls=true&file=<?php echo $mp4; ?>" /> 		
				<!-- Image fall back for non-HTML5 browser with JavaScript turned off and no Flash player installed -->
				<img src="<?php echo jeg_get_image($cover, '', $width, $height); ?>" title="<?php _e('No video playback capabilities', 'jegtheme')?>" />
			</object>
		</video>
	</div>
	<div class="item-description">
		<div class="item-desc-wrapper">
			<h2><?php echo $title; ?></h2>
			
			<?php 
			if(j_get_option('social_sharer')) :
				echo $socialblock;
			endif; 
			?>
			
			<span><?php echo implode(', ', $catlist)?></span>
			<div class="wrapper-text"><?php echo $content; ?></div>
		</div>
		<div class="item-navigator">
			<a href="" data-tourl="false">
				<div class="item-prev" title="<?php j_e('portfolio_prev', "Previous Portfolio")?>">
					<div class="icon-chevron-left item-icon-prev">&nbsp;</div>
				</div>
			</a>
			<a href="" data-tourl="false">
				<div class="item-next" title="<?php j_e('portfolio_next', "Next Portfolio")?>">			
					<div class="icon-chevron-right item-icon-next">&nbsp;</div>
				</div>
			</a>
		</div>
	</div>
</div>