<div class="setting-option">	
	<h4 class="setting-title"><?php echo $title ?> :</h4>		
	<textarea name="<?php echo $id?>"><?php echo $value; ?></textarea>
	<span class="meta-description"><?php echo $description; ?></span>
	
	<?php if(isset($help)) : ?>
	<div class="moreinfo" title="More Info">&nbsp;</div>
	<div class="help">
		<div class="help-wrapper">
			<?php echo $help; ?>
		</div>
	</div>
	<?php endif; ?>
</div>