<div class="setting-option">	
	<h4 class="setting-title"><?php echo $title ?>:</h4>	
	<?php echo j_create_metabox_nonce($id); ?>
	<?php foreach ($option as $key => $val) : ?>	
	<div class="checkbox-wrapper">		
		<?php $checked = in_array($key, $value) ? "checked='checked'" : '' ; ?> 
		<input type="checkbox" value="<?php echo $key; ?>" name="<?php echo $id; ?>[]" id="<?php echo $id . $key; ?>" <?php echo $checked; ?> />	
		<label for="<?php echo $id . $key; ?>"><?php echo $val; ?></label>
	</div>
	<?php endforeach; ?>
	<span class="meta-description"><?php echo $description; ?></span>
	
	<?php if(isset($help)) : ?>
	<div class="moreinfo" title="More Info">&nbsp;</div>
	<div class="help">
		<div class="help-wrapper">
			<?php echo $help; ?>
		</div>
	</div>
	<?php endif; ?>
	
</div>