<div class="setting-option">	
	<h4 class="setting-title"><?php echo $title ?> :</h4>	
	
	<div class="uploadfile">		
		<input type="text" class="uploadtext" name="<?php echo $id; ?>" id="<?php echo $id; ?>" value="<?php echo $value; ?>" />
		<input type="button" value="Select File" class="selectfile"/>
	</div>	
	
	<span class="meta-description"><?php echo $description; ?></span>
	
	<?php if(isset($help)) : ?>
	<div class="moreinfo" title="More Info">&nbsp;</div>
	<div class="help">
		<div class="help-wrapper">
			<?php echo $help; ?>
		</div>
	</div>
	<?php endif; ?>
</div>